### PR TITLE
Export ModuleListFile in bootstrap

### PR DESCRIPTION
**Pull request by c-parsons**

### CODE REVIEW

**Comment by colincross** [comment]
Changes look good, but we usually squash the updates and force push the new version.

**Comment by c-parsons** [comment]
I'm not quite sure I understand the process. You squash several pull requests and force push changes as a "release" ? (If I'm understanding correctly, when can I expect this?)

**Comment by colincross** [comment]
No, you squash your 3 commits in this pull request into one commit, and then reupload that as your modulelistfile branch.  You'll have to use `git push -f` to upload it because it is rewriting the history of your branch.

**Comment by c-parsons** [comment]
Hmm, I thought the "Squash and merge" [flow](https://cloudfour.com/thinks/squashing-your-pull-requests/) on github handled this for you?

**Pull request merged**
