### PR TITLE
Replace README.md with an archival announcement.

### PR DESCRIPTION
**Pull request by lberki**

### CODE REVIEW

**Comment by jin** [comment]
cc @hicksjoseph

**Review by jin — APPROVED** [review]
👍 LGTM, please also get a review from @hicksjoseph.

**Comment by kaladron** [comment]
Thanks for handling this!

**Comment by lberki** [comment]
Actually, I just realize that I should go through AOSP for this, too. Closing this in favor of https://android-review.googlesource.com/c/platform/build/blueprint/+/1655694/ .

**Pull request closed without merging**
