### PR TITLE
Enforce gofmt in travis

### PR DESCRIPTION
**Pull request by colincross**
Run gofmt -l . during travis to catch pull requests that have not had
gofmt run on them.

Change-Id: Ibfdf988a535d82721f3c4bc328b189f606f12778

### CODE REVIEW

**Comment by danw** [comment]
LGTM

**Comment by colincross** [comment]
Rebased on top of "Fix gofmt" patch from #113 so the travis check passes.

**Comment by colincross** [comment]
And made it print the gofmt errors.

**Comment by danw** [comment]
LGTM

**Pull request merged**
